#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjNlZGYwMDA5YWUyNzc0NzAzYWRlOWM0YjY3YTg1MmVmOTBhNThmMzQzYjEyMTc1YjU5NTYyNzY2NTJhOGM5NTUwZjQ3OWRlYzQ1ODNkYjVhNTIwN2ViMDYzYmZjNzM3NjkxOA==
management:
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
